### ISSUE TITLE
wait for imu...

### ISSUE THREAD

**Issue by Fran-FC** [zinuok/VINS-Fusion-ROS2#10]
When running the node it gets blocked by "waiting for imu..." loop, though my imu is being published correctly.

```
fran@fran-msi:~/Coding/tb4_ws$ ros2 topic hz /imu
average rate: 100.383
	min: 0.002s max: 0.016s std dev: 0.00359s window: 101
```

```YAML
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu"
image0_topic: "/oakd/left/image_raw"
image1_topic: "/oakd/right/image_raw"
output_path: "/home/fran/Coding/vins-fusion_ws/src/VINS-Fusion-ROS2"
```
